1. Conociendo los datos

```{r}
#1.1
install.packages("tidyverse")
#1.2
library(tidyverse)

yearly <- read_csv("deaths_handwashing.csv")
#1.3
yearly
```
2. El alarmante número de muertes

```{r}
#2.1
yearly <- yearly %>%
  mutate(proportions_deaths = deaths/births)
#2.2
yearly
```
3. Muerte en las clínicas

```{r}
yearly
  #3.1 y 3.2
ggplot(yearly, aes(x=year, y=proportions_deaths, color=clinic))+
geom_line()
```
4. Comienza el lavado de manos
4.1
```{r}
monthly <- read_csv("deaths_clinic_1.csv")
#4.2
monthly <- monthly %>%
  mutate(proportion_deaths = deaths/births)
#4.3
head(monthly)
```
5. El efecto del lavado de manos

```{r}
monthly
#5.1-5.2
ggplot(monthly, aes(x=date, y=proportion_deaths))+
  geom_line()+
  labs(title = "Efecto del lavado de manos (proporción de muertes por fecha)", y="Proportion of deaths")+
  labs(x= "DATE")
#5.3
mean_by_year <- monthly %>%
  group_by(date) %>%
  summarize(death_by_year=mean(proportion_deaths))

mean_by_year
#5.4
ggplot(mean_by_year, aes(x=death_by_year))+
  geom_histogram(bins = 50)

```
6. Los resultados del lavado de manos
6.1
```{r}
monthly <- monthly %>%
  mutate(handwashing_started = if_else(date >= "1847-01-01", TRUE, FALSE))

monthly
#6.2 - 6.3
ggplot(monthly, aes(x=date, y=proportion_deaths, color=handwashing_started))+
  geom_line()+
  labs(title = "Hands washing since 1847", y="Proportion of deaths")+
  labs(x= "DATE")
```
7. ¿Más lavado de manos, menos muertes?
7.1-7.2-7.3
```{r}
monthly %>%
  group_by(handwashing_started) %>%
  summarize(month_summary=mean(proportion_deaths))

```
8. Análisis estadístico de los datos de lavado de manos

```{r}
monthly

t.test(proportion_deaths ~ handwashing_started, data = monthly, conf_level = 0.95)
```

